export type League = 'NBA' | 'NFL' | 'MLB' | 'MLS' | 'UEFA' | 'NHL';

export interface TeamMeta {
    league: League;
    slug: string;           // short code used in file name, e.g. 'lal', 'nyk', 'real-madrid'
    name: string;           // canonical full name, e.g. 'Los Angeles Lakers'
    aliases: string[];      // common variants: ['Lakers', 'LA Lakers']
    logoPath: string;       // e.g. '/logos/nba/lal.svg'
}

export const TEAMS: TeamMeta[] = [
    // NBA
    { league: 'NBA', slug: 'atl', name: 'Atlanta Hawks', aliases: ['Hawks'], logoPath: '/logos/NBA/ATL.png' },
    { league: 'NBA', slug: 'bos', name: 'Boston Celtics', aliases: ['Celtics'], logoPath: '/logos/NBA/BOS.png' },
    { league: 'NBA', slug: 'bkn', name: 'Brooklyn Nets', aliases: ['Nets'], logoPath: '/logos/NBA/BKN.png' },
    { league: 'NBA', slug: 'cha', name: 'Charlotte Hornets', aliases: ['Hornets'], logoPath: '/logos/NBA/CHAH.png' },
    { league: 'NBA', slug: 'chi', name: 'Chicago Bulls', aliases: ['Bulls'], logoPath: '/logos/NBA/CHIH.png' },
    { league: 'NBA', slug: 'cle', name: 'Cleveland Cavaliers', aliases: ['Cavaliers', 'Cavs'], logoPath: '/logos/NBA/CLEH.png' },
    { league: 'NBA', slug: 'dal', name: 'Dallas Mavericks', aliases: ['Mavericks', 'Mavs'], logoPath: '/logos/NBA/DALH.png' },
    { league: 'NBA', slug: 'den', name: 'Denver Nuggets', aliases: ['Nuggets'], logoPath: '/logos/NBA/DENH.png' },
    { league: 'NBA', slug: 'det', name: 'Detroit Pistons', aliases: ['Pistons'], logoPath: '/logos/NBA/DETH.png' },
    { league: 'NBA', slug: 'gsw', name: 'Golden State Warriors', aliases: ['Warriors'], logoPath: '/logos/NBA/GSH.png' },
    { league: 'NBA', slug: 'hou', name: 'Houston Rockets', aliases: ['Rockets'], logoPath: '/logos/NBA/HOU.png' },
    { league: 'NBA', slug: 'ind', name: 'Indiana Pacers', aliases: ['Pacers'], logoPath: '/logos/NBA/IND.png' },
    { league: 'NBA', slug: 'lac', name: 'Los Angeles Clippers', aliases: ['Clippers', 'LA Clippers', 'L.A. Clippers'], logoPath: '/logos/NBA/LACH.png' },
    { league: 'NBA', slug: 'lal', name: 'Los Angeles Lakers', aliases: ['Lakers', 'LA Lakers', 'L.A. Lakers'], logoPath: '/logos/NBA/LAL.png' },
    { league: 'NBA', slug: 'mem', name: 'Memphis Grizzlies', aliases: ['Grizzlies', 'Grizz'], logoPath: '/logos/NBA/MEMH.png' },
    { league: 'NBA', slug: 'mia', name: 'Miami Heat', aliases: ['Heat'], logoPath: '/logos/NBA/MIAH.png' },
    { league: 'NBA', slug: 'mil', name: 'Milwaukee Bucks', aliases: ['Bucks'], logoPath: '/logos/NBA/MILH.png' },
    { league: 'NBA', slug: 'min', name: 'Minnesota Timberwolves', aliases: ['Timberwolves', 'Wolves'], logoPath: '/logos/NBA/MINH.png' },
    { league: 'NBA', slug: 'nop', name: 'New Orleans Pelicans', aliases: ['Pelicans', 'Pels'], logoPath: '/logos/NBA/NO.png' },
    { league: 'NBA', slug: 'nyk', name: 'New York Knicks', aliases: ['Knicks'], logoPath: '/logos/NBA/NY.png' },
    { league: 'NBA', slug: 'okc', name: 'Oklahoma City Thunder', aliases: ['Thunder', 'OKC'], logoPath: '/logos/NBA/OKCH.png' },
    { league: 'NBA', slug: 'orl', name: 'Orlando Magic', aliases: ['Magic'], logoPath: '/logos/NBA/ORL.png' },
    { league: 'NBA', slug: 'phi', name: 'Philadelphia 76ers', aliases: ['76ers', 'Sixers'], logoPath: '/logos/NBA/PHIH.png' },
    { league: 'NBA', slug: 'phx', name: 'Phoenix Suns', aliases: ['Suns'], logoPath: '/logos/NBA/PHX.png' },
    { league: 'NBA', slug: 'por', name: 'Portland Trail Blazers', aliases: ['Blazers'], logoPath: '/logos/NBA/PORH.png' },
    { league: 'NBA', slug: 'sac', name: 'Sacramento Kings', aliases: ['Kings'], logoPath: '/logos/NBA/SACH.png' },
    { league: 'NBA', slug: 'sas', name: 'San Antonio Spurs', aliases: ['Spurs'], logoPath: '/logos/NBA/SAH.png' },
    { league: 'NBA', slug: 'tor', name: 'Toronto Raptors', aliases: ['Raptors', 'Raps'], logoPath: '/logos/NBA/TORH.png' },
    { league: 'NBA', slug: 'uta', name: 'Utah Jazz', aliases: ['Jazz'], logoPath: '/logos/NBA/UTAHH.png' },
    { league: 'NBA', slug: 'was', name: 'Washington Wizards', aliases: ['Wizards'], logoPath: '/logos/NBA/WSH.png' },

    // NFL
    { league: 'NFL', slug: 'ari', name: 'Arizona Cardinals', aliases: ['Cardinals'], logoPath: '/logos/NFL/ARI.png' },
    { league: 'NFL', slug: 'atl', name: 'Atlanta Falcons', aliases: ['Falcons'], logoPath: '/logos/NFL/ATL.png' },
    { league: 'NFL', slug: 'bal', name: 'Baltimore Ravens', aliases: ['Ravens'], logoPath: '/logos/NFL/BAL.png' },
    { league: 'NFL', slug: 'buf', name: 'Buffalo Bills', aliases: ['Bills'], logoPath: '/logos/NFL/BUF.png' },
    { league: 'NFL', slug: 'car', name: 'Carolina Panthers', aliases: ['Panthers'], logoPath: '/logos/NFL/CAR.png' },
    { league: 'NFL', slug: 'chi', name: 'Chicago Bears', aliases: ['Bears'], logoPath: '/logos/NFL/CHI.png' },
    { league: 'NFL', slug: 'cin', name: 'Cincinnati Bengals', aliases: ['Bengals'], logoPath: '/logos/NFL/CIN.png' },
    { league: 'NFL', slug: 'cle', name: 'Cleveland Browns', aliases: ['Browns'], logoPath: '/logos/NFL/CLE.png' },
    { league: 'NFL', slug: 'dal', name: 'Dallas Cowboys', aliases: ['Cowboys'], logoPath: '/logos/NFL/DAL.png' },
    { league: 'NFL', slug: 'den', name: 'Denver Broncos', aliases: ['Broncos'], logoPath: '/logos/NFL/DEN.png' },
    { league: 'NFL', slug: 'det', name: 'Detroit Lions', aliases: ['Lions'], logoPath: '/logos/NFL/DET.png' },
    { league: 'NFL', slug: 'gb', name: 'Green Bay Packers', aliases: ['Packers'], logoPath: '/logos/NFL/GB.png' },
    { league: 'NFL', slug: 'hou', name: 'Houston Texans', aliases: ['Texans'], logoPath: '/logos/NFL/HOU.png' },
    { league: 'NFL', slug: 'ind', name: 'Indianapolis Colts', aliases: ['Colts'], logoPath: '/logos/NFL/IND.png' },
    { league: 'NFL', slug: 'jax', name: 'Jacksonville Jaguars', aliases: ['Jaguars', 'Jags'], logoPath: '/logos/NFL/JAX.png' },
    { league: 'NFL', slug: 'kc', name: 'Kansas City Chiefs', aliases: ['Chiefs'], logoPath: '/logos/NFL/KC.png' },
    { league: 'NFL', slug: 'lv', name: 'Las Vegas Raiders', aliases: ['Raiders'], logoPath: '/logos/NFL/LV.png' },
    { league: 'NFL', slug: 'lac', name: 'Los Angeles Chargers', aliases: ['Chargers', 'LA Chargers'], logoPath: '/logos/NFL/LAC.png' },
    { league: 'NFL', slug: 'lar', name: 'Los Angeles Rams', aliases: ['Rams', 'LA Rams'], logoPath: '/logos/NFL/LAR.png' },
    { league: 'NFL', slug: 'mia', name: 'Miami Dolphins', aliases: ['Dolphins', 'Fins'], logoPath: '/logos/NFL/MIA.png' },
    { league: 'NFL', slug: 'min', name: 'Minnesota Vikings', aliases: ['Vikings'], logoPath: '/logos/NFL/MIN.png' },
    { league: 'NFL', slug: 'ne', name: 'New England Patriots', aliases: ['Patriots', 'Pats'], logoPath: '/logos/NFL/NE.png' },
    { league: 'NFL', slug: 'no', name: 'New Orleans Saints', aliases: ['Saints'], logoPath: '/logos/NFL/NO.png' },
    { league: 'NFL', slug: 'nyg', name: 'New York Giants', aliases: ['Giants', 'NY Giants'], logoPath: '/logos/NFL/NYG.png' },
    { league: 'NFL', slug: 'nyj', name: 'New York Jets', aliases: ['Jets', 'NY Jets'], logoPath: '/logos/NFL/NYJ.png' },
    { league: 'NFL', slug: 'phi', name: 'Philadelphia Eagles', aliases: ['Eagles', 'Philly'], logoPath: '/logos/NFL/PHI.png' },
    { league: 'NFL', slug: 'pit', name: 'Pittsburgh Steelers', aliases: ['Steelers'], logoPath: '/logos/NFL/PIT.png' },
    { league: 'NFL', slug: 'sf', name: 'San Francisco 49ers', aliases: ['49ers', 'Niners'], logoPath: '/logos/NFL/SF.png' },
    { league: 'NFL', slug: 'sea', name: 'Seattle Seahawks', aliases: ['Seahawks', 'Hawks'], logoPath: '/logos/NFL/SEA.png' },
    { league: 'NFL', slug: 'tb', name: 'Tampa Bay Buccaneers', aliases: ['Buccaneers', 'Bucs'], logoPath: '/logos/NFL/TB.png' },
    { league: 'NFL', slug: 'ten', name: 'Tennessee Titans', aliases: ['Titans'], logoPath: '/logos/NFL/TEN.png' },
    { league: 'NFL', slug: 'wsh', name: 'Washington Commanders', aliases: ['Commanders'], logoPath: '/logos/NFL/WSH.png' },

    // MLB
    { league: 'MLB', slug: 'angels', name: 'Los Angeles Angels', aliases: ['Angels', 'LA Angels'], logoPath: '/logos/MLB/angels.png' },
    { league: 'MLB', slug: 'astros', name: 'Houston Astros', aliases: ['Astros'], logoPath: '/logos/MLB/astros.png' },
    { league: 'MLB', slug: 'athletics', name: 'Oakland Athletics', aliases: ['Athletics', 'A\'s'], logoPath: '/logos/MLB/athletics.png' },
    { league: 'MLB', slug: 'blueJays', name: 'Toronto Blue Jays', aliases: ['Blue Jays', 'Jays'], logoPath: '/logos/MLB/blueJays.png' },
    { league: 'MLB', slug: 'braves', name: 'Atlanta Braves', aliases: ['Braves'], logoPath: '/logos/MLB/braves.png' },
    { league: 'MLB', slug: 'brewers', name: 'Milwaukee Brewers', aliases: ['Brewers'], logoPath: '/logos/MLB/brewers.png' },
    { league: 'MLB', slug: 'cardinals', name: 'St. Louis Cardinals', aliases: ['Cardinals', 'Cards'], logoPath: '/logos/MLB/cardinals.png' },
    { league: 'MLB', slug: 'cubs', name: 'Chicago Cubs', aliases: ['Cubs'], logoPath: '/logos/MLB/cubs.png' },
    { league: 'MLB', slug: 'diamondbacks', name: 'Arizona Diamondbacks', aliases: ['Diamondbacks', 'D-backs'], logoPath: '/logos/MLB/diamondbacks.png' },
    { league: 'MLB', slug: 'dodgers', name: 'Los Angeles Dodgers', aliases: ['Dodgers', 'LA Dodgers'], logoPath: '/logos/MLB/dodgers.png' },
    { league: 'MLB', slug: 'giants', name: 'San Francisco Giants', aliases: ['Giants'], logoPath: '/logos/MLB/giants.png' },
    { league: 'MLB', slug: 'indians', name: 'Cleveland Guardians', aliases: ['Guardians', 'Indians'], logoPath: '/logos/MLB/indians.png' },
    { league: 'MLB', slug: 'mariners', name: 'Seattle Mariners', aliases: ['Mariners'], logoPath: '/logos/MLB/mariners.png' },
    { league: 'MLB', slug: 'marlins', name: 'Miami Marlins', aliases: ['Marlins'], logoPath: '/logos/MLB/marlins.png' },
    { league: 'MLB', slug: 'mets', name: 'New York Mets', aliases: ['Mets'], logoPath: '/logos/MLB/mets.png' },
    { league: 'MLB', slug: 'nationals', name: 'Washington Nationals', aliases: ['Nationals', 'Nats'], logoPath: '/logos/MLB/nationals.png' },
    { league: 'MLB', slug: 'orioles', name: 'Baltimore Orioles', aliases: ['Orioles', 'O\'s'], logoPath: '/logos/MLB/orioles.png' },
    { league: 'MLB', slug: 'padres', name: 'San Diego Padres', aliases: ['Padres'], logoPath: '/logos/MLB/padres.png' },
    { league: 'MLB', slug: 'phillies', name: 'Philadelphia Phillies', aliases: ['Phillies', 'Phils'], logoPath: '/logos/MLB/phillies.png' },
    { league: 'MLB', slug: 'pirates', name: 'Pittsburgh Pirates', aliases: ['Pirates', 'Buccos'], logoPath: '/logos/MLB/pirates.png' },
    { league: 'MLB', slug: 'rangers', name: 'Texas Rangers', aliases: ['Rangers'], logoPath: '/logos/MLB/rangers.png' },
    { league: 'MLB', slug: 'rays', name: 'Tampa Bay Rays', aliases: ['Rays'], logoPath: '/logos/MLB/rays.png' },
    { league: 'MLB', slug: 'reds', name: 'Cincinnati Reds', aliases: ['Reds'], logoPath: '/logos/MLB/reds.png' },
    { league: 'MLB', slug: 'redSox', name: 'Boston Red Sox', aliases: ['Red Sox', 'Sox'], logoPath: '/logos/MLB/redSox.png' },
    { league: 'MLB', slug: 'rockies', name: 'Colorado Rockies', aliases: ['Rockies'], logoPath: '/logos/MLB/rockies.png' },
    { league: 'MLB', slug: 'royals', name: 'Kansas City Royals', aliases: ['Royals'], logoPath: '/logos/MLB/royals.png' },
    { league: 'MLB', slug: 'tigers', name: 'Detroit Tigers', aliases: ['Tigers'], logoPath: '/logos/MLB/tigers.png' },
    { league: 'MLB', slug: 'twins', name: 'Minnesota Twins', aliases: ['Twins'], logoPath: '/logos/MLB/twins.png' },
    { league: 'MLB', slug: 'whiteSox', name: 'Chicago White Sox', aliases: ['White Sox', 'Sox'], logoPath: '/logos/MLB/whiteSox.png' },
    { league: 'MLB', slug: 'yankees', name: 'New York Yankees', aliases: ['Yankees', 'NY Yankees'], logoPath: '/logos/MLB/yankees.png' },

    // MLS
    { league: 'MLS', slug: 'ame', name: 'Club América', aliases: ['América', 'Club América'], logoPath: '/logos/MLS/AME.png' },
    { league: 'MLS', slug: 'atl', name: 'Atlanta United FC', aliases: ['Atlanta United'], logoPath: '/logos/MLS/ATL.png' },
    { league: 'MLS', slug: 'ats', name: 'Atlético San Luis', aliases: ['Atlético San Luis', 'San Luis'], logoPath: '/logos/MLS/ATS.png' },
    { league: 'MLS', slug: 'atx', name: 'Austin FC', aliases: ['Austin FC'], logoPath: '/logos/MLS/ATX.png' },
    { league: 'MLS', slug: 'caz', name: 'Cruz Azul', aliases: ['Cruz Azul'], logoPath: '/logos/MLS/CAZ.png' },
    { league: 'MLS', slug: 'chi', name: 'Chicago Fire FC', aliases: ['Chicago Fire'], logoPath: '/logos/MLS/CHI.png' },
    { league: 'MLS', slug: 'cin', name: 'FC Cincinnati', aliases: ['FC Cincinnati'], logoPath: '/logos/MLS/CIN.png' },
    { league: 'MLS', slug: 'clb', name: 'Columbus Crew SC', aliases: ['Columbus Crew', 'Crew'], logoPath: '/logos/MLS/CLB.png' },
    { league: 'MLS', slug: 'clt', name: 'Charlotte FC', aliases: ['Charlotte FC'], logoPath: '/logos/MLS/CLT.png' },
    { league: 'MLS', slug: 'col', name: 'Colorado Rapids', aliases: ['Colorado Rapids', 'Rapids'], logoPath: '/logos/MLS/COL.png' },
    { league: 'MLS', slug: 'dal', name: 'FC Dallas', aliases: ['FC Dallas'], logoPath: '/logos/MLS/DAL.png' },
    { league: 'MLS', slug: 'dc', name: 'D.C. United', aliases: ['DC United', 'D.C. United'], logoPath: '/logos/MLS/DC.png' },
    { league: 'MLS', slug: 'hou', name: 'Houston Dynamo FC', aliases: ['Houston Dynamo', 'Dynamo'], logoPath: '/logos/MLS/HOU.png' },
    { league: 'MLS', slug: 'jua', name: 'FC Juárez', aliases: ['FC Juárez', 'Juárez'], logoPath: '/logos/MLS/JUA.png' },
    { league: 'MLS', slug: 'la', name: 'LA Galaxy', aliases: ['LA Galaxy', 'Galaxy'], logoPath: '/logos/MLS/LA.png' },
    { league: 'MLS', slug: 'lafc', name: 'Los Angeles FC', aliases: ['LAFC', 'Los Angeles FC'], logoPath: '/logos/MLS/LAFC.png' },
    { league: 'MLS', slug: 'maz', name: 'Mazatlán FC', aliases: ['Mazatlán', 'Mazatlán FC'], logoPath: '/logos/MLS/MAZ.png' },
    { league: 'MLS', slug: 'mia', name: 'Inter Miami CF', aliases: ['Inter Miami'], logoPath: '/logos/MLS/MIA.png' },
    { league: 'MLS', slug: 'min', name: 'Minnesota United FC', aliases: ['Minnesota United'], logoPath: '/logos/MLS/MIN.png' },
    { league: 'MLS', slug: 'mtl', name: 'CF Montréal', aliases: ['CF Montréal', 'Montréal', 'Montreal'], logoPath: '/logos/MLS/MTL.png' },
    { league: 'MLS', slug: 'ne', name: 'New England Revolution', aliases: ['New England Revolution', 'Revolution'], logoPath: '/logos/MLS/NE.png' },
    { league: 'MLS', slug: 'nsh', name: 'Nashville SC', aliases: ['Nashville SC'], logoPath: '/logos/MLS/NSH.png' },
    { league: 'MLS', slug: 'nyc', name: 'New York City FC', aliases: ['New York City', 'NYC'], logoPath: '/logos/MLS/NYC.png' },
    { league: 'MLS', slug: 'nyr', name: 'New York Red Bulls', aliases: ['New York Red Bulls', 'Red Bulls'], logoPath: '/logos/MLS/NYR.png' },
    { league: 'MLS', slug: 'orl', name: 'Orlando City SC', aliases: ['Orlando City'], logoPath: '/logos/MLS/ORL.png' },
    { league: 'MLS', slug: 'phi', name: 'Philadelphia Union', aliases: ['Philadelphia Union', 'Union'], logoPath: '/logos/MLS/PHI.png' },
    { league: 'MLS', slug: 'por', name: 'Portland Timbers', aliases: ['Portland Timbers', 'Timbers'], logoPath: '/logos/MLS/POR.png' },
    { league: 'MLS', slug: 'qro', name: 'Querétaro FC', aliases: ['Querétaro', 'Querétaro FC'], logoPath: '/logos/MLS/QRO.png' },
    { league: 'MLS', slug: 'rsl', name: 'Real Salt Lake', aliases: ['Real Salt Lake', 'Salt Lake'], logoPath: '/logos/MLS/RSL.png' },
    { league: 'MLS', slug: 'san', name: 'San Jose Earthquakes', aliases: ['San Jose Earthquakes', 'Earthquakes', 'Quakes'], logoPath: '/logos/MLS/SAN.png' },
    { league: 'MLS', slug: 'sea', name: 'Seattle Sounders FC', aliases: ['Seattle Sounders', 'Sounders'], logoPath: '/logos/MLS/SEA.png' },
    { league: 'MLS', slug: 'skc', name: 'Sporting Kansas City', aliases: ['Sporting KC'], logoPath: '/logos/MLS/SKC.png' },
    { league: 'MLS', slug: 'stl', name: 'St. Louis City SC', aliases: ['St. Louis City', 'St. Louis'], logoPath: '/logos/MLS/STL.png' },
    { league: 'MLS', slug: 'tij', name: 'Club Tijuana', aliases: ['Club Tijuana', 'Tijuana'], logoPath: '/logos/MLS/TIJ.png' },
    { league: 'MLS', slug: 'tor', name: 'Toronto FC', aliases: ['Toronto FC'], logoPath: '/logos/MLS/TOR.png' },
    { league: 'MLS', slug: 'uanl', name: 'Tigres UANL', aliases: ['Tigres UANL', 'Tigres'], logoPath: '/logos/MLS/UANL.png' },
    { league: 'MLS', slug: 'unam', name: 'Pumas UNAM', aliases: ['Pumas UNAM', 'UNAM'], logoPath: '/logos/MLS/UNAM.png' },
    { league: 'MLS', slug: 'van', name: 'Vancouver Whitecaps FC', aliases: ['Vancouver Whitecaps', 'Whitecaps'], logoPath: '/logos/MLS/VAN.png' },

    // UEFA
    { league: 'UEFA', slug: 'ars', name: 'Arsenal', aliases: ['Arsenal FC'], logoPath: '/logos/UEFA/ARS.png' },
    { league: 'UEFA', slug: 'ata', name: 'Atalanta BC', aliases: ['Atalanta', 'Atalanta BC'], logoPath: '/logos/UEFA/ATA.png' },
    { league: 'UEFA', slug: 'atm', name: 'Atlético Madrid', aliases: ['Atlético Madrid', 'Atletico Madrid'], logoPath: '/logos/UEFA/ATM.png' },
    { league: 'UEFA', slug: 'avl', name: 'Aston Villa', aliases: ['Aston Villa', 'Villa'], logoPath: '/logos/UEFA/AVL.png' },
    { league: 'UEFA', slug: 'b04', name: 'Bayer Leverkusen', aliases: ['Bayer Leverkusen', 'Leverkusen'], logoPath: '/logos/UEFA/B04.png' },
    { league: 'UEFA', slug: 'bar', name: 'FC Barcelona', aliases: ['Barcelona', 'Barça', 'FC Barcelona'], logoPath: '/logos/UEFA/BAR.png' },
    { league: 'UEFA', slug: 'ben', name: 'Benfica', aliases: ['SL Benfica'], logoPath: '/logos/UEFA/BEN.png' },
    { league: 'UEFA', slug: 'bkh', name: 'BK Häcken', aliases: ['BK Häcken', 'Häcken'], logoPath: '/logos/UEFA/BKH.png' },
    { league: 'UEFA', slug: 'bol', name: 'Bologna FC', aliases: ['Bologna', 'Bologna FC'], logoPath: '/logos/UEFA/BOL.png' },
    { league: 'UEFA', slug: 'bre', name: 'Stade Brestois', aliases: ['Brest', 'Stade Brestois'], logoPath: '/logos/UEFA/BRE.png' },
    { league: 'UEFA', slug: 'bru', name: 'Club Brugge', aliases: ['Club Brugge', 'Brugge'], logoPath: '/logos/UEFA/BRU.png' },
    { league: 'UEFA', slug: 'cel', name: 'Celtic', aliases: ['Celtic', 'Celtic FC'], logoPath: '/logos/UEFA/CEL.png' },
    { league: 'UEFA', slug: 'dzg', name: 'Dinamo Zagreb', aliases: ['Dinamo Zagreb', 'Dinamo'], logoPath: '/logos/UEFA/DZG.png' },
    { league: 'UEFA', slug: 'fey', name: 'Feyenoord', aliases: [], logoPath: '/logos/UEFA/FEY.png' },
    { league: 'UEFA', slug: 'gir', name: 'Girona FC', aliases: ['Girona', 'Girona FC'], logoPath: '/logos/UEFA/GIR.png' },
    { league: 'UEFA', slug: 'int', name: 'Inter Milan', aliases: ['Inter Milan', 'Internazionale'], logoPath: '/logos/UEFA/INT.png' },
    { league: 'UEFA', slug: 'juv', name: 'Juventus', aliases: ['Juve'], logoPath: '/logos/UEFA/JUV.png' },
    { league: 'UEFA', slug: 'lill', name: 'Lille OSC', aliases: ['Lille', 'Lille OSC'], logoPath: '/logos/UEFA/LILL.png' },
    { league: 'UEFA', slug: 'liv', name: 'Liverpool', aliases: ['Liverpool FC'], logoPath: '/logos/UEFA/LIV.png' },
    { league: 'UEFA', slug: 'mil', name: 'AC Milan', aliases: ['AC Milan', 'Milan'], logoPath: '/logos/UEFA/MIL.png' },
    { league: 'UEFA', slug: 'mnc', name: 'Manchester City', aliases: ['Man City', 'Man. City'], logoPath: '/logos/UEFA/MNC.png' },
    { league: 'UEFA', slug: 'mon', name: 'AS Monaco', aliases: ['Monaco', 'AS Monaco'], logoPath: '/logos/UEFA/MON.png' },
    { league: 'UEFA', slug: 'psg', name: 'Paris Saint-Germain', aliases: ['PSG', 'Paris Saint-Germain', 'Paris SG'], logoPath: '/logos/UEFA/PSG.png' },
    { league: 'UEFA', slug: 'psv', name: 'PSV Eindhoven', aliases: ['PSV', 'PSV Eindhoven'], logoPath: '/logos/UEFA/PSV.png' },
    { league: 'UEFA', slug: 'rbl', name: 'Red Bull Leipzig', aliases: ['RB Leipzig', 'Leipzig'], logoPath: '/logos/UEFA/RBL.png' },
    { league: 'UEFA', slug: 'rma', name: 'Real Madrid', aliases: ['Real Madrid CF'], logoPath: '/logos/UEFA/RMA.png' },
    { league: 'UEFA', slug: 'rsb', name: 'Red Bull Salzburg', aliases: ['RB Salzburg', 'Salzburg'], logoPath: '/logos/UEFA/RSB.png' },
    { league: 'UEFA', slug: 'scp', name: 'Sporting CP', aliases: ['Sporting CP', 'Sporting'], logoPath: '/logos/UEFA/SCP.png' },
    { league: 'UEFA', slug: 'shk', name: 'Shakhtar Donetsk', aliases: ['Shakhtar', 'Shakhtar Donetsk'], logoPath: '/logos/UEFA/SHK.png' },
    { league: 'UEFA', slug: 'slb', name: 'Slavia Prague', aliases: ['Slavia'], logoPath: '/logos/UEFA/SLB.png' },
    { league: 'UEFA', slug: 'slz', name: 'Slovan Bratislava', aliases: ['Slovan Bratislava', 'Slovan'], logoPath: '/logos/UEFA/SLZ.png' },
    { league: 'UEFA', slug: 'spp', name: 'Sparta Prague', aliases: ['Sparta'], logoPath: '/logos/UEFA/SPP.png' },
    { league: 'UEFA', slug: 'stg', name: 'Sturm Graz', aliases: ['Sturm Graz', 'Sturm'], logoPath: '/logos/UEFA/STG.png' },
    { league: 'UEFA', slug: 'vfb', name: 'VfB Stuttgart', aliases: ['Stuttgart', 'VfB Stuttgart'], logoPath: '/logos/UEFA/VFB.png' },
    { league: 'UEFA', slug: 'yb', name: 'Young Boys', aliases: ['YB Bern'], logoPath: '/logos/UEFA/YB.png' },

    // NHL
    { league: 'NHL', slug: 'ana', name: 'Anaheim Ducks', aliases: ['Ducks'], logoPath: '/logos/NHL/ana.png' },
    { league: 'NHL', slug: 'ari', name: 'Arizona Coyotes', aliases: ['Coyotes'], logoPath: '/logos/NHL/ari.png' },
    { league: 'NHL', slug: 'bos', name: 'Boston Bruins', aliases: ['Bruins'], logoPath: '/logos/NHL/bos.png' },
    { league: 'NHL', slug: 'buf', name: 'Buffalo Sabres', aliases: ['Sabres'], logoPath: '/logos/NHL/buf.png' },
    { league: 'NHL', slug: 'cgy', name: 'Calgary Flames', aliases: ['Flames'], logoPath: '/logos/NHL/cgy.png' },
    { league: 'NHL', slug: 'car', name: 'Carolina Hurricanes', aliases: ['Hurricanes', 'Canes'], logoPath: '/logos/NHL/car.png' },
    { league: 'NHL', slug: 'chi', name: 'Chicago Blackhawks', aliases: ['Blackhawks', 'Black Hawks'], logoPath: '/logos/NHL/chi.png' },
    { league: 'NHL', slug: 'cbj', name: 'Columbus Blue Jackets', aliases: ['Blue Jackets'], logoPath: '/logos/NHL/cbj.png' },
    { league: 'NHL', slug: 'col', name: 'Colorado Avalanche', aliases: ['Avalanche', 'Avs'], logoPath: '/logos/NHL/col.png' },
    { league: 'NHL', slug: 'dal', name: 'Dallas Stars', aliases: ['Stars'], logoPath: '/logos/NHL/dal.png' },
    { league: 'NHL', slug: 'det', name: 'Detroit Red Wings', aliases: ['Red Wings', 'Wings'], logoPath: '/logos/NHL/det.png' },
    { league: 'NHL', slug: 'edm', name: 'Edmonton Oilers', aliases: ['Oilers'], logoPath: '/logos/NHL/edm.png' },
    { league: 'NHL', slug: 'fla', name: 'Florida Panthers', aliases: ['Panthers'], logoPath: '/logos/NHL/fla.png' },
    { league: 'NHL', slug: 'lak', name: 'Los Angeles Kings', aliases: ['Kings', 'LA Kings'], logoPath: '/logos/NHL/lak.png' },
    { league: 'NHL', slug: 'min', name: 'Minnesota Wild', aliases: ['Wild'], logoPath: '/logos/NHL/min.png' },
    { league: 'NHL', slug: 'mtl', name: 'Montreal Canadiens', aliases: ['Canadiens', 'Habs'], logoPath: '/logos/NHL/mtl.png' },
    { league: 'NHL', slug: 'njd', name: 'New Jersey Devils', aliases: ['Devils'], logoPath: '/logos/NHL/njd.png' },
    { league: 'NHL', slug: 'nsh', name: 'Nashville Predators', aliases: ['Predators'], logoPath: '/logos/NHL/nsh.png' },
    { league: 'NHL', slug: 'nyi', name: 'New York Islanders', aliases: ['Islanders', 'NY Islanders'], logoPath: '/logos/NHL/nyi.png' },
    { league: 'NHL', slug: 'nyr', name: 'New York Rangers', aliases: ['Rangers', 'NY Rangers'], logoPath: '/logos/NHL/nyr.png' },
    { league: 'NHL', slug: 'ott', name: 'Ottawa Senators', aliases: ['Senators'], logoPath: '/logos/NHL/ott.png' },
    { league: 'NHL', slug: 'phi', name: 'Philadelphia Flyers', aliases: ['Flyers'], logoPath: '/logos/NHL/phi.png' },
    { league: 'NHL', slug: 'pit', name: 'Pittsburgh Penguins', aliases: ['Penguins', 'Pens'], logoPath: '/logos/NHL/pit.png' },
    { league: 'NHL', slug: 'sea', name: 'Seattle Kraken', aliases: ['Kraken'], logoPath: '/logos/NHL/sea.png' },
    { league: 'NHL', slug: 'sj', name: 'San Jose Sharks', aliases: ['Sharks'], logoPath: '/logos/NHL/sj.png' },
    { league: 'NHL', slug: 'stl', name: 'St. Louis Blues', aliases: ['Blues'], logoPath: '/logos/NHL/stl.png' },
    { league: 'NHL', slug: 'tbl', name: 'Tampa Bay Lightning', aliases: ['Lightning'], logoPath: '/logos/NHL/tbl.png' },
    { league: 'NHL', slug: 'tor', name: 'Toronto Maple Leafs', aliases: ['Maple Leafs', 'Leafs'], logoPath: '/logos/NHL/tor.png' },
    { league: 'NHL', slug: 'van', name: 'Vancouver Canucks', aliases: ['Canucks'], logoPath: '/logos/NHL/van.png' },
    { league: 'NHL', slug: 'veg', name: 'Vegas Golden Knights', aliases: ['Golden Knights', 'Knights'], logoPath: '/logos/NHL/veg.png' },
    { league: 'NHL', slug: 'wpg', name: 'Winnipeg Jets', aliases: ['Jets'], logoPath: '/logos/NHL/wpg.png' },
    { league: 'NHL', slug: 'wsh', name: 'Washington Capitals', aliases: ['Capitals'], logoPath: '/logos/NHL/wsh.png' },
];
